services:
  - type: web
    name: eyeai-diagnostic-platform
    env: python
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers=4 --timeout=120 run_server:app
    envVars:
      - key: RENDER
        value: "true"
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: GEMINI_API_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true
