# Simple web service configuration
services:
  - type: web
    name: eyeai-diagnostic-platform
    plan: free
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run_server:app --log-file=- --access-logfile=- --error-logfile=- --capture-output
    envVars:
      - key: RENDER
        value: "true"
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: "3.9.0"
      - key: GEMINI_API_KEY
        sync: false
    # Make sure we have proper Python version
    runtime: python3
